{
  "code": 0,
  "msg": "",
  "data": [{
    "title": "主页",
    "icon": "layui-icon-home",
    "jump": "/iframe/box/index"
  },{
    "name": "",
    "title": "搜一下",
    "icon": "layui-icon-search",
    "jump": "/iframe/search/index"
  }, {
    "name": "",
    "title": "听音乐",
    "icon": "layui-icon-headset",
    "jump": "/iframe/music/index"
  }, {
    "name": "shipin",
    "title": "看视频",
    "icon": "layui-icon-play",
    "list": [{
      "name": "",
      "title": "哔哩哔哩",
      "jump": "/iframe/video/bilibili"
    }, {
      "name": "",
      "title": "央视网",
      "jump": "/iframe/video/cctv"
    }, {
      "name": "",
      "title": "风行网",
      "jump": "/iframe/video/fengxing"
    }, {
      "name": "",
      "title": "爱奇艺",
      "jump": "/iframe/video/iqiyi"
    }, {
      "name": "",
      "title": "乐视视频",
      "jump": "/iframe/video/le"
    }, {
      "name": "",
      "title": "芒果tv",
      "jump": "/iframe/video/mgtv"
    }, {
      "name": "",
      "title": "PP视频",
      "jump": "/iframe/video/pptv"
    }, {
      "name": "",
      "title": "腾讯视频",
      "jump": "/iframe/video/qq"
    }, {
      "name": "",
      "title": "搜狐视频",
      "jump": "/iframe/video/sohu"
    }, {
      "name": "",
      "title": "-土豆视频-",
      "jump": "/iframe/video/tudou"
    }, {
      "name": "",
      "title": "-优酷视频-",
      "jump": "/iframe/video/youku"
    }]
  }, {
    "name": "soft",
    "title": "云软件",
    "icon": "layui-icon-app",
    "jump": "/iframe/soft/cloudsoft"
  }, {
    "name": "component",
    "title": "更多",
    "icon": "layui-icon-senior",
    "list": [{
      "name": "",
      "title": "微信头像",
      "jump": "/iframe/wechat-head/index"
    }, {
      "name": "",
      "title": "工作桌面",
      "jump": "/iframe/generate-effective-desktop/index"
    }, {
      "name": "",
      "title": "工具",
      "jump": "website/tools"
    }]
  }, {
    "name": "",
    "title": "网站大事件",
    "icon": "layui-icon-tips",
    "jump": "/iframe/timeline"
  }]
}